[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "14.17.3"
  NPM_VERSION = "6.14.13"
  HUGO_VERSION = "0.85.0"

[context.production]
  command = "npm run build"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"
